import Mathlib.RingTheory.Polynomial.UniqueFactorization

open scoped BigOperators
open Ideal MvPolynomial

/-
Formalize in Lean the Theorem (radical_span_singleton_eq_span_prod_irreducibles) from Text.

The theorem must be named `radical_span_singleton_eq_span_prod_irreducibles`.
Matched text (candidate 0, theorem, label=radical_span_singleton_eq_span_prod_irreducibles):
\begin{theorem}[radical_span_singleton_eq_span_prod_irreducibles]\label{prop:radical-principal}
Let $f \in k[x_1,\dots,x_n]$ and let $I=\langle f\rangle$ be the principal ideal generated by $f$.
If
\[
f = c\, f_1^{a_1}\cdots f_r^{a_r}
\]
is a factorization of $f$ into a product of \emph{distinct} irreducible polynomials
(with $c\in k$ and $a_i\ge 1$), then
\[
\sqrt{I}=\sqrt{\langle f\rangle}=\langle f_1 f_2\cdots f_r\rangle.
\]
\end{theorem}
-/

theorem radical_span_singleton_eq_span_prod_irreducibles_boya
    {k : Type*} [Field k] {n : ℕ}
    (f : MvPolynomial (Fin n) k) (c : k)
    (factors : List (MvPolynomial (Fin n) k)) (exps : List ℕ)
    (hlen : factors.length = exps.length)
    (hirred : ∀ p ∈ factors, Irreducible p)
    (hdist : factors.Pairwise (fun p q => ¬ Associated p q))
    (hpos : ∀ e ∈ exps, 0 < e)
    (hf : f = C c * (List.zipWith (fun p e => p ^ e) factors exps).prod) :
    (span {f}).radical = span {factors.prod} := by
/-
\begin{proof}
First we show that $f_1 f_2\cdots f_r \in \sqrt{I}$. Choose an integer $N$ strictly larger than $\max\{a_1,\dots,a_r\}$. Then \[ c (f_1 f_2\cdots f_r)^N = f_1^{N-a_1} f_2^{N-a_2}\cdots f_r^{N-a_r}\, f, \] so $(f_1 f_2\cdots f_r)^N \in I$, hence $f_1 f_2\cdots f_r \in \sqrt{I}$. Therefore $\langle f_1 f_2\cdots f_r\rangle \subseteq \sqrt{I}$.

For the reverse inclusion, let $g\in \sqrt{I}$. Then $g^M\in I=\langle f\rangle$ for some positive integer $M$, so $g^M$ is divisible by $f$ and hence by each irreducible factor $f_i$. Using unique factorization (and that irreducibles behave as primes here), each $f_i$ must divide $g$, so $f_1 f_2\cdots f_r$ divides $g$. Thus $g\in \langle f_1 f_2\cdots f_r\rangle$, i.e. $\sqrt{I}\subseteq \langle f_1 f_2\cdots f_r\rangle$.
\end{proof}
-/
  let facexp := List.zipWith (fun p e => p ^ e) factors exps
  apply le_antisymm
  · -- Direction 2: √I ⊆ ⟨∏fᵢ⟩
    -- Let $g\in \sqrt{I}$
    -- hence each fᵢ ∣ g^M, hence each fᵢ ∣ g (prime), hence ∏fᵢ ∣ g.
    intro g hg
    rw [Ideal.mem_radical_iff] at hg
    -- Then $g^M\in I=\langle f\rangle$ for some positive integer $M$, so $g^M$ is divisible by $f$
    rcases hg with ⟨M, hgM⟩
    rw [Ideal.mem_span_singleton] at hgM ⊢
    -- f ∣ g^M, so each fᵢ^eᵢ ∣ g^M (since fᵢ^eᵢ ∣ f)
    rw [hf] at hgM
    apply dvd_of_mul_left_dvd at hgM
    have hdvd_facexp_gpow : ∀ pe ∈ facexp, pe ∣ g ^ M := by
      intro pe hpe
      exact dvd_trans (List.dvd_prod hpe) hgM
    -- Each fᵢ is prime, so fᵢ ∣ g^M ⟹ fᵢ ∣ g
    have hprime : ∀ p ∈ factors, Prime p := by
      intro p hp
      exact (UniqueFactorizationMonoid.irreducible_iff_prime.mp (hirred p hp))

    -- Then the fᵢ are pairwise coprime (non-associated irreducibles = primes)
    -- so their product divides g


    #check Prime.dvd_of_dvd_pow

    #check IsCoprime.mul_dvd

    -- Assume: hp : p ∈ factors, hgM : f ∣ g^M, hf : f = C c * (zipWith ...).prod
    -- Goal: ∃ e, 0 < e ∧ p ^ e ∣ g ^ M

    obtain ⟨e, he_mem, rfl, rfl, rfl⟩ := ... -- pair p with its exponent e

    have hei_dvd_gM : p ^ e ∣ g ^ M :=
      calc p ^ e
          ∣ (List.zipWith (fun p e => p ^ e) factors exps).prod :=
              List.dvd_prod_of_mem _ (List.mem_zipWith.mpr ⟨p, e, hp, he_mem, rfl⟩)
        _ ∣ f := by rw [hf]; exact dvd_mul_of_dvd_right dvd_rfl _
        _ ∣ g ^ M := hgM

    suffices h : ∀ (l : List (MvPolynomial (Fin n) k)),
        (∀ p ∈ l, Irreducible p) →
        l.Pairwise (fun p q => ¬Associated p q) →
        (∀ p ∈ l, p ∣ g) →
        l.prod ∣ g by
      apply h factors hirred hdist
      intro p hp
      -- p is prime
      have hprime : Prime p :=
        (UniqueFactorizationMonoid.irreducible_iff_prime.mp (hirred p hp))
      -- f ∣ g^M and p ∣ f, so p ∣ g^M
      have hpf : p ∣ f := by
        rw [hf]
        apply dvd_mul_of_dvd_right
        apply List.dvd_prod_of_mem
        -- p^e ∣ ∏(fᵢ^eᵢ), and p ∣ p^e
        obtain ⟨e, he_mem, he_zip⟩ : ∃ e ∈ exps, List.zipWith
              (fun p e => p ^ e) factors exps |>.get
              ⟨factors.indexOf p, by simp [List.indexOf_lt_length.mpr hp]⟩ = p ^ e := by
          sorry
        sorry
      exact hprime.dvd_of_dvd_pow (hpf.trans hgM)
    -- Prove by induction: pairwise coprime list, each divides g ⟹ product divides g
    intro l
    induction l with
    | nil => simp
    | cons q qs ih =>
      intro hlirred hlpair hldvd
      simp only [List.prod_cons]
      have hqdvd : q ∣ g := hldvd q (List.mem_cons_self q qs)
      have hqsdvd : qs.prod ∣ g :=
        ih (fun p hp => hlirred p (List.mem_cons_of_mem q hp))
           hlpair.tail
           (fun p hp => hldvd p (List.mem_cons_of_mem q hp))
      -- q and qs.prod are coprime: q is prime, not associated to any factor in qs
      have hcoprime : IsCoprime q qs.prod := by
        have hqprime : Prime q :=
          UniqueFactorizationMonoid.irreducible_iff_prime.mp
            (hlirred q (List.mem_cons_self q qs))
        rw [hqprime.coprime_iff_not_dvd]
        intro hqqs
        -- q ∣ qs.prod ⟹ q ∣ some qᵢ ∈ qs ⟹ q ~ qᵢ, contradicting hdist
        have : ∃ qi ∈ qs, q ∣ qi := by
          have := hqprime.dvd_prod_iff (l := qs) |>.mp hqqs
          obtain ⟨qi, hqi_mem, hqi_dvd⟩ := this
          exact ⟨qi, hqi_mem, hqi_dvd⟩
        obtain ⟨qi, hqi_mem, hqi_dvd⟩ := this
        have hqi_irred : Irreducible qi :=
          hlirred qi (List.mem_cons_of_mem q hqi_mem)
        have hassoc : Associated q qi :=
          (hqprime.irreducible.associated_of_dvd hqi_irred hqi_dvd)
        exact hlpair.rel_head' hqi_mem hassoc
      exact hcoprime.mul_dvd hqdvd hqsdvd
  · -- Direction 1: ⟨∏fᵢ⟩ ⊆ √I
    -- (∏fᵢ)^N ∈ ⟨f⟩ for N > max(aᵢ), via c·(∏fᵢ)^N = (∏fᵢ^(N-aᵢ))·f
    rw [Ideal.span_singleton_le_iff_mem]
    rw [Ideal.mem_radical_iff]
    -- Choose N = (exps.foldr max 0) + 1
    set N := exps.foldr max 0 + 1 with hN_def
    use N
    constructor
    · omega
    · rw [Ideal.mem_span_singleton]
      -- Need f ∣ (∏fᵢ)^N
      -- We have f = C c * ∏fᵢ^aᵢ
      -- (∏fᵢ)^N = ∏fᵢ^N
      -- Each fᵢ^aᵢ ∣ fᵢ^N since aᵢ ≤ N-1 < N
      -- So ∏fᵢ^aᵢ ∣ ∏fᵢ^N = (∏fᵢ)^N
      -- Hence C c * ∏fᵢ^aᵢ ∣ (∏fᵢ)^N iff C c is a unit... but we need c ≠ 0
      -- The argument from the proof: c·(∏fᵢ)^N = (∏fᵢ^(N-aᵢ))·f
      -- so f ∣ (∏fᵢ)^N in the ring (given c is a unit).
      -- Key identity: C c * (∏fᵢ)^N = (∏fᵢ^(N-aᵢ)) * f
      -- Hence f ∣ C c * (∏fᵢ)^N, and C c unit ⟹ f ∣ (∏fᵢ)^N
      sorry


  · sorry
  · apply span_le.mpr
  have ge : ∀ p ∈ factors, p ∈ (span {f}).radical := by sorry
  have : span {factors.prod} ≤ (span {f}).radical := by
    apply span_le.mpr
    sorry

  have le : (span {f}).radical = span {factors.prod} := by sorry
  #check TwoSidedIdeal.le_iff
  sorry

-- https://gemini.google.com/share/eead3cd7b4c6
